sudo: required

services:
  - docker

matrix:
  include:
    - name: stable
      env:
        - TOOLCHAIN=stable
        - TAG_LATEST=1
    - name: nightly
      env: TOOLCHAIN=nightly
    - name: beta
      env: TOOLCHAIN=beta
script:
  - docker build --build-arg TOOLCHAIN=${TOOLCHAIN} -t wafflespeanut/rust-wasm-builder:${TOOLCHAIN} .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push wafflespeanut/rust-wasm-builder:${TOOLCHAIN}
  - if [[ ! -z $TAG_LATEST ]]; then docker tag "wafflespeanut/rust-wasm-builder:$TOOLCHAIN" "wafflespeanut/rust-wasm-builder:latest" && docker push wafflespeanut/rust-wasm-builder; fi
