sudo: required

services:
  - docker

sudo: required

services:
  - docker

matrix:
  include:
    - name: stable
      env: TOOLCHAIN=stable
    - name: nightly
      env: TOOLCHAIN=nightly
script:
  - docker build --build-arg TOOLCHAIN=${TOOLCHAIN} -t wafflespeanut/rust-wasm-builder:${TOOLCHAIN} .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push wafflespeanut/rust-wasm-builder:${TOOLCHAIN}
